// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: artist.proto

package artistpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Artist_GetArtist_FullMethodName       = "/mangahub.artist.v1.Artist/GetArtist"
	Artist_CreateArtist_FullMethodName    = "/mangahub.artist.v1.Artist/CreateArtist"
	Artist_UpdateArtist_FullMethodName    = "/mangahub.artist.v1.Artist/UpdateArtist"
	Artist_DeleteArtist_FullMethodName    = "/mangahub.artist.v1.Artist/DeleteArtist"
	Artist_ListArtist_FullMethodName      = "/mangahub.artist.v1.Artist/ListArtist"
	Artist_SearchArtist_FullMethodName    = "/mangahub.artist.v1.Artist/SearchArtist"
	Artist_ListArtistManga_FullMethodName = "/mangahub.artist.v1.Artist/ListArtistManga"
)

// ArtistClient is the client API for Artist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtistClient interface {
	GetArtist(ctx context.Context, in *GetArtistRequest, opts ...grpc.CallOption) (*ArtistEntity, error)
	CreateArtist(ctx context.Context, in *CreateArtistRequest, opts ...grpc.CallOption) (*ArtistEntity, error)
	UpdateArtist(ctx context.Context, in *UpdateArtistRequest, opts ...grpc.CallOption) (*ArtistEntity, error)
	DeleteArtist(ctx context.Context, in *DeleteArtistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListArtist(ctx context.Context, in *ListArtistRequest, opts ...grpc.CallOption) (*ListArtistResponse, error)
	SearchArtist(ctx context.Context, in *SearchArtistRequest, opts ...grpc.CallOption) (*ListArtistResponse, error)
	ListArtistManga(ctx context.Context, in *ListArtistMangaRequest, opts ...grpc.CallOption) (*ListArtistMangaResponse, error)
}

type artistClient struct {
	cc grpc.ClientConnInterface
}

func NewArtistClient(cc grpc.ClientConnInterface) ArtistClient {
	return &artistClient{cc}
}

func (c *artistClient) GetArtist(ctx context.Context, in *GetArtistRequest, opts ...grpc.CallOption) (*ArtistEntity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtistEntity)
	err := c.cc.Invoke(ctx, Artist_GetArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistClient) CreateArtist(ctx context.Context, in *CreateArtistRequest, opts ...grpc.CallOption) (*ArtistEntity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtistEntity)
	err := c.cc.Invoke(ctx, Artist_CreateArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistClient) UpdateArtist(ctx context.Context, in *UpdateArtistRequest, opts ...grpc.CallOption) (*ArtistEntity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtistEntity)
	err := c.cc.Invoke(ctx, Artist_UpdateArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistClient) DeleteArtist(ctx context.Context, in *DeleteArtistRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Artist_DeleteArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistClient) ListArtist(ctx context.Context, in *ListArtistRequest, opts ...grpc.CallOption) (*ListArtistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArtistResponse)
	err := c.cc.Invoke(ctx, Artist_ListArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistClient) SearchArtist(ctx context.Context, in *SearchArtistRequest, opts ...grpc.CallOption) (*ListArtistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArtistResponse)
	err := c.cc.Invoke(ctx, Artist_SearchArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artistClient) ListArtistManga(ctx context.Context, in *ListArtistMangaRequest, opts ...grpc.CallOption) (*ListArtistMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArtistMangaResponse)
	err := c.cc.Invoke(ctx, Artist_ListArtistManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtistServer is the server API for Artist service.
// All implementations must embed UnimplementedArtistServer
// for forward compatibility.
type ArtistServer interface {
	GetArtist(context.Context, *GetArtistRequest) (*ArtistEntity, error)
	CreateArtist(context.Context, *CreateArtistRequest) (*ArtistEntity, error)
	UpdateArtist(context.Context, *UpdateArtistRequest) (*ArtistEntity, error)
	DeleteArtist(context.Context, *DeleteArtistRequest) (*emptypb.Empty, error)
	ListArtist(context.Context, *ListArtistRequest) (*ListArtistResponse, error)
	SearchArtist(context.Context, *SearchArtistRequest) (*ListArtistResponse, error)
	ListArtistManga(context.Context, *ListArtistMangaRequest) (*ListArtistMangaResponse, error)
	mustEmbedUnimplementedArtistServer()
}

// UnimplementedArtistServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtistServer struct{}

func (UnimplementedArtistServer) GetArtist(context.Context, *GetArtistRequest) (*ArtistEntity, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtist not implemented")
}
func (UnimplementedArtistServer) CreateArtist(context.Context, *CreateArtistRequest) (*ArtistEntity, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArtist not implemented")
}
func (UnimplementedArtistServer) UpdateArtist(context.Context, *UpdateArtistRequest) (*ArtistEntity, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArtist not implemented")
}
func (UnimplementedArtistServer) DeleteArtist(context.Context, *DeleteArtistRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArtist not implemented")
}
func (UnimplementedArtistServer) ListArtist(context.Context, *ListArtistRequest) (*ListArtistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArtist not implemented")
}
func (UnimplementedArtistServer) SearchArtist(context.Context, *SearchArtistRequest) (*ListArtistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArtist not implemented")
}
func (UnimplementedArtistServer) ListArtistManga(context.Context, *ListArtistMangaRequest) (*ListArtistMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArtistManga not implemented")
}
func (UnimplementedArtistServer) mustEmbedUnimplementedArtistServer() {}
func (UnimplementedArtistServer) testEmbeddedByValue()                {}

// UnsafeArtistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtistServer will
// result in compilation errors.
type UnsafeArtistServer interface {
	mustEmbedUnimplementedArtistServer()
}

func RegisterArtistServer(s grpc.ServiceRegistrar, srv ArtistServer) {
	// If the following call panics, it indicates UnimplementedArtistServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Artist_ServiceDesc, srv)
}

func _Artist_GetArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServer).GetArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Artist_GetArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServer).GetArtist(ctx, req.(*GetArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artist_CreateArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServer).CreateArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Artist_CreateArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServer).CreateArtist(ctx, req.(*CreateArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artist_UpdateArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServer).UpdateArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Artist_UpdateArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServer).UpdateArtist(ctx, req.(*UpdateArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artist_DeleteArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServer).DeleteArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Artist_DeleteArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServer).DeleteArtist(ctx, req.(*DeleteArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artist_ListArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServer).ListArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Artist_ListArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServer).ListArtist(ctx, req.(*ListArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artist_SearchArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServer).SearchArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Artist_SearchArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServer).SearchArtist(ctx, req.(*SearchArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Artist_ListArtistManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtistMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtistServer).ListArtistManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Artist_ListArtistManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtistServer).ListArtistManga(ctx, req.(*ListArtistMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Artist_ServiceDesc is the grpc.ServiceDesc for Artist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Artist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mangahub.artist.v1.Artist",
	HandlerType: (*ArtistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArtist",
			Handler:    _Artist_GetArtist_Handler,
		},
		{
			MethodName: "CreateArtist",
			Handler:    _Artist_CreateArtist_Handler,
		},
		{
			MethodName: "UpdateArtist",
			Handler:    _Artist_UpdateArtist_Handler,
		},
		{
			MethodName: "DeleteArtist",
			Handler:    _Artist_DeleteArtist_Handler,
		},
		{
			MethodName: "ListArtist",
			Handler:    _Artist_ListArtist_Handler,
		},
		{
			MethodName: "SearchArtist",
			Handler:    _Artist_SearchArtist_Handler,
		},
		{
			MethodName: "ListArtistManga",
			Handler:    _Artist_ListArtistManga_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "artist.proto",
}
