// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: artist.proto

package artistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtistEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalIds   map[string]string      `protobuf:"bytes,2,rep,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // artist | author | both
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	MangaIds      []string               `protobuf:"bytes,6,rep,name=manga_ids,json=mangaIds,proto3" json:"manga_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistEntity) Reset() {
	*x = ArtistEntity{}
	mi := &file_artist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistEntity) ProtoMessage() {}

func (x *ArtistEntity) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistEntity.ProtoReflect.Descriptor instead.
func (*ArtistEntity) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{0}
}

func (x *ArtistEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtistEntity) GetExternalIds() map[string]string {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *ArtistEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtistEntity) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ArtistEntity) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ArtistEntity) GetMangaIds() []string {
	if x != nil {
		return x.MangaIds
	}
	return nil
}

func (x *ArtistEntity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ArtistEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtistRequest) Reset() {
	*x = GetArtistRequest{}
	mi := &file_artist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistRequest) ProtoMessage() {}

func (x *GetArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistRequest.ProtoReflect.Descriptor instead.
func (*GetArtistRequest) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{1}
}

func (x *GetArtistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *ArtistEntity          `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtistRequest) Reset() {
	*x = CreateArtistRequest{}
	mi := &file_artist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtistRequest) ProtoMessage() {}

func (x *CreateArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtistRequest.ProtoReflect.Descriptor instead.
func (*CreateArtistRequest) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArtistRequest) GetArtist() *ArtistEntity {
	if x != nil {
		return x.Artist
	}
	return nil
}

type DeleteArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtistRequest) Reset() {
	*x = DeleteArtistRequest{}
	mi := &file_artist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtistRequest) ProtoMessage() {}

func (x *DeleteArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtistRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtistRequest) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteArtistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArtistPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NameSet       bool                   `protobuf:"varint,2,opt,name=name_set,json=nameSet,proto3" json:"name_set,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	RoleSet       bool                   `protobuf:"varint,4,opt,name=role_set,json=roleSet,proto3" json:"role_set,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	BioSet        bool                   `protobuf:"varint,6,opt,name=bio_set,json=bioSet,proto3" json:"bio_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistPatch) Reset() {
	*x = ArtistPatch{}
	mi := &file_artist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistPatch) ProtoMessage() {}

func (x *ArtistPatch) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistPatch.ProtoReflect.Descriptor instead.
func (*ArtistPatch) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{4}
}

func (x *ArtistPatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtistPatch) GetNameSet() bool {
	if x != nil {
		return x.NameSet
	}
	return false
}

func (x *ArtistPatch) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ArtistPatch) GetRoleSet() bool {
	if x != nil {
		return x.RoleSet
	}
	return false
}

func (x *ArtistPatch) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ArtistPatch) GetBioSet() bool {
	if x != nil {
		return x.BioSet
	}
	return false
}

type UpdateArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Patch         *ArtistPatch           `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArtistRequest) Reset() {
	*x = UpdateArtistRequest{}
	mi := &file_artist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtistRequest) ProtoMessage() {}

func (x *UpdateArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtistRequest.ProtoReflect.Descriptor instead.
func (*UpdateArtistRequest) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateArtistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateArtistRequest) GetPatch() *ArtistPatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

type ListArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtistRequest) Reset() {
	*x = ListArtistRequest{}
	mi := &file_artist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtistRequest) ProtoMessage() {}

func (x *ListArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtistRequest.ProtoReflect.Descriptor instead.
func (*ListArtistRequest) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{6}
}

func (x *ListArtistRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArtistRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArtistRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type SearchArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArtistRequest) Reset() {
	*x = SearchArtistRequest{}
	mi := &file_artist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArtistRequest) ProtoMessage() {}

func (x *SearchArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArtistRequest.ProtoReflect.Descriptor instead.
func (*SearchArtistRequest) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{7}
}

func (x *SearchArtistRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchArtistRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchArtistRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListArtistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ArtistEntity        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtistResponse) Reset() {
	*x = ListArtistResponse{}
	mi := &file_artist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtistResponse) ProtoMessage() {}

func (x *ListArtistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtistResponse.ProtoReflect.Descriptor instead.
func (*ListArtistResponse) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{8}
}

func (x *ListArtistResponse) GetItems() []*ArtistEntity {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListArtistResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArtistResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArtistResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListArtistMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistId      string                 `protobuf:"bytes,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtistMangaRequest) Reset() {
	*x = ListArtistMangaRequest{}
	mi := &file_artist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtistMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtistMangaRequest) ProtoMessage() {}

func (x *ListArtistMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtistMangaRequest.ProtoReflect.Descriptor instead.
func (*ListArtistMangaRequest) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{9}
}

func (x *ListArtistMangaRequest) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *ListArtistMangaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArtistMangaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// MangaSummary is a minimal projection used by ListArtistManga so that
// artist-svc does not need to depend on the full catalog Manga message.
type MangaSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Chapters      int32                  `protobuf:"varint,5,opt,name=chapters,proto3" json:"chapters,omitempty"`
	Rating        float64                `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Popularity    int32                  `protobuf:"varint,7,opt,name=popularity,proto3" json:"popularity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaSummary) Reset() {
	*x = MangaSummary{}
	mi := &file_artist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaSummary) ProtoMessage() {}

func (x *MangaSummary) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaSummary.ProtoReflect.Descriptor instead.
func (*MangaSummary) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{10}
}

func (x *MangaSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MangaSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MangaSummary) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *MangaSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MangaSummary) GetChapters() int32 {
	if x != nil {
		return x.Chapters
	}
	return 0
}

func (x *MangaSummary) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MangaSummary) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

type ListArtistMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MangaSummary        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtistMangaResponse) Reset() {
	*x = ListArtistMangaResponse{}
	mi := &file_artist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtistMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtistMangaResponse) ProtoMessage() {}

func (x *ListArtistMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtistMangaResponse.ProtoReflect.Descriptor instead.
func (*ListArtistMangaResponse) Descriptor() ([]byte, []int) {
	return file_artist_proto_rawDescGZIP(), []int{11}
}

func (x *ListArtistMangaResponse) GetItems() []*MangaSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListArtistMangaResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArtistMangaResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArtistMangaResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_artist_proto protoreflect.FileDescriptor

const file_artist_proto_rawDesc = "" +
	"\n" +
	"\fartist.proto\x12\x12mangahub.artist.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x03\n" +
	"\fArtistEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12T\n" +
	"\fexternal_ids\x18\x02 \x03(\v21.mangahub.artist.v1.ArtistEntity.ExternalIdsEntryR\vexternalIds\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1b\n" +
	"\tmanga_ids\x18\x06 \x03(\tR\bmangaIds\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a>\n" +
	"\x10ExternalIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\"\n" +
	"\x10GetArtistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x13CreateArtistRequest\x128\n" +
	"\x06artist\x18\x01 \x01(\v2 .mangahub.artist.v1.ArtistEntityR\x06artist\"%\n" +
	"\x13DeleteArtistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x96\x01\n" +
	"\vArtistPatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bname_set\x18\x02 \x01(\bR\anameSet\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x19\n" +
	"\brole_set\x18\x04 \x01(\bR\aroleSet\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x17\n" +
	"\abio_set\x18\x06 \x01(\bR\x06bioSet\"\\\n" +
	"\x13UpdateArtistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x05patch\x18\x02 \x01(\v2\x1f.mangahub.artist.v1.ArtistPatchR\x05patch\"K\n" +
	"\x11ListArtistRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\"U\n" +
	"\x13SearchArtistRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8c\x01\n" +
	"\x12ListArtistResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .mangahub.artist.v1.ArtistEntityR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"_\n" +
	"\x16ListArtistMangaRequest\x12\x1b\n" +
	"\tartist_id\x18\x01 \x01(\tR\bartistId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xbd\x01\n" +
	"\fMangaSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bchapters\x18\x05 \x01(\x05R\bchapters\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x01R\x06rating\x12\x1e\n" +
	"\n" +
	"popularity\x18\a \x01(\x05R\n" +
	"popularity\"\x91\x01\n" +
	"\x17ListArtistMangaResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .mangahub.artist.v1.MangaSummaryR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total2\x8e\x05\n" +
	"\x06Artist\x12S\n" +
	"\tGetArtist\x12$.mangahub.artist.v1.GetArtistRequest\x1a .mangahub.artist.v1.ArtistEntity\x12Y\n" +
	"\fCreateArtist\x12'.mangahub.artist.v1.CreateArtistRequest\x1a .mangahub.artist.v1.ArtistEntity\x12Y\n" +
	"\fUpdateArtist\x12'.mangahub.artist.v1.UpdateArtistRequest\x1a .mangahub.artist.v1.ArtistEntity\x12O\n" +
	"\fDeleteArtist\x12'.mangahub.artist.v1.DeleteArtistRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\n" +
	"ListArtist\x12%.mangahub.artist.v1.ListArtistRequest\x1a&.mangahub.artist.v1.ListArtistResponse\x12_\n" +
	"\fSearchArtist\x12'.mangahub.artist.v1.SearchArtistRequest\x1a&.mangahub.artist.v1.ListArtistResponse\x12j\n" +
	"\x0fListArtistManga\x12*.mangahub.artist.v1.ListArtistMangaRequest\x1a+.mangahub.artist.v1.ListArtistMangaResponseB*Z(mangahub-backend/proto/artistpb;artistpbb\x06proto3"

var (
	file_artist_proto_rawDescOnce sync.Once
	file_artist_proto_rawDescData []byte
)

func file_artist_proto_rawDescGZIP() []byte {
	file_artist_proto_rawDescOnce.Do(func() {
		file_artist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artist_proto_rawDesc), len(file_artist_proto_rawDesc)))
	})
	return file_artist_proto_rawDescData
}

var file_artist_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_artist_proto_goTypes = []any{
	(*ArtistEntity)(nil),            // 0: mangahub.artist.v1.ArtistEntity
	(*GetArtistRequest)(nil),        // 1: mangahub.artist.v1.GetArtistRequest
	(*CreateArtistRequest)(nil),     // 2: mangahub.artist.v1.CreateArtistRequest
	(*DeleteArtistRequest)(nil),     // 3: mangahub.artist.v1.DeleteArtistRequest
	(*ArtistPatch)(nil),             // 4: mangahub.artist.v1.ArtistPatch
	(*UpdateArtistRequest)(nil),     // 5: mangahub.artist.v1.UpdateArtistRequest
	(*ListArtistRequest)(nil),       // 6: mangahub.artist.v1.ListArtistRequest
	(*SearchArtistRequest)(nil),     // 7: mangahub.artist.v1.SearchArtistRequest
	(*ListArtistResponse)(nil),      // 8: mangahub.artist.v1.ListArtistResponse
	(*ListArtistMangaRequest)(nil),  // 9: mangahub.artist.v1.ListArtistMangaRequest
	(*MangaSummary)(nil),            // 10: mangahub.artist.v1.MangaSummary
	(*ListArtistMangaResponse)(nil), // 11: mangahub.artist.v1.ListArtistMangaResponse
	nil,                             // 12: mangahub.artist.v1.ArtistEntity.ExternalIdsEntry
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 14: google.protobuf.Empty
}
var file_artist_proto_depIdxs = []int32{
	12, // 0: mangahub.artist.v1.ArtistEntity.external_ids:type_name -> mangahub.artist.v1.ArtistEntity.ExternalIdsEntry
	13, // 1: mangahub.artist.v1.ArtistEntity.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: mangahub.artist.v1.ArtistEntity.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: mangahub.artist.v1.CreateArtistRequest.artist:type_name -> mangahub.artist.v1.ArtistEntity
	4,  // 4: mangahub.artist.v1.UpdateArtistRequest.patch:type_name -> mangahub.artist.v1.ArtistPatch
	0,  // 5: mangahub.artist.v1.ListArtistResponse.items:type_name -> mangahub.artist.v1.ArtistEntity
	10, // 6: mangahub.artist.v1.ListArtistMangaResponse.items:type_name -> mangahub.artist.v1.MangaSummary
	1,  // 7: mangahub.artist.v1.Artist.GetArtist:input_type -> mangahub.artist.v1.GetArtistRequest
	2,  // 8: mangahub.artist.v1.Artist.CreateArtist:input_type -> mangahub.artist.v1.CreateArtistRequest
	5,  // 9: mangahub.artist.v1.Artist.UpdateArtist:input_type -> mangahub.artist.v1.UpdateArtistRequest
	3,  // 10: mangahub.artist.v1.Artist.DeleteArtist:input_type -> mangahub.artist.v1.DeleteArtistRequest
	6,  // 11: mangahub.artist.v1.Artist.ListArtist:input_type -> mangahub.artist.v1.ListArtistRequest
	7,  // 12: mangahub.artist.v1.Artist.SearchArtist:input_type -> mangahub.artist.v1.SearchArtistRequest
	9,  // 13: mangahub.artist.v1.Artist.ListArtistManga:input_type -> mangahub.artist.v1.ListArtistMangaRequest
	0,  // 14: mangahub.artist.v1.Artist.GetArtist:output_type -> mangahub.artist.v1.ArtistEntity
	0,  // 15: mangahub.artist.v1.Artist.CreateArtist:output_type -> mangahub.artist.v1.ArtistEntity
	0,  // 16: mangahub.artist.v1.Artist.UpdateArtist:output_type -> mangahub.artist.v1.ArtistEntity
	14, // 17: mangahub.artist.v1.Artist.DeleteArtist:output_type -> google.protobuf.Empty
	8,  // 18: mangahub.artist.v1.Artist.ListArtist:output_type -> mangahub.artist.v1.ListArtistResponse
	8,  // 19: mangahub.artist.v1.Artist.SearchArtist:output_type -> mangahub.artist.v1.ListArtistResponse
	11, // 20: mangahub.artist.v1.Artist.ListArtistManga:output_type -> mangahub.artist.v1.ListArtistMangaResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_artist_proto_init() }
func file_artist_proto_init() {
	if File_artist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artist_proto_rawDesc), len(file_artist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artist_proto_goTypes,
		DependencyIndexes: file_artist_proto_depIdxs,
		MessageInfos:      file_artist_proto_msgTypes,
	}.Build()
	File_artist_proto = out.File
	file_artist_proto_goTypes = nil
	file_artist_proto_depIdxs = nil
}
