// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: prefs.proto

package prefspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Preferences struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FavoriteGenres []string               `protobuf:"bytes,2,rep,name=favorite_genres,json=favoriteGenres,proto3" json:"favorite_genres,omitempty"`
	Language       string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Nsfw           bool                   `protobuf:"varint,4,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Preferences) Reset() {
	*x = Preferences{}
	mi := &file_prefs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preferences) ProtoMessage() {}

func (x *Preferences) ProtoReflect() protoreflect.Message {
	mi := &file_prefs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preferences.ProtoReflect.Descriptor instead.
func (*Preferences) Descriptor() ([]byte, []int) {
	return file_prefs_proto_rawDescGZIP(), []int{0}
}

func (x *Preferences) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Preferences) GetFavoriteGenres() []string {
	if x != nil {
		return x.FavoriteGenres
	}
	return nil
}

func (x *Preferences) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Preferences) GetNsfw() bool {
	if x != nil {
		return x.Nsfw
	}
	return false
}

func (x *Preferences) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Room          string                 `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_prefs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_prefs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_prefs_proto_rawDescGZIP(), []int{1}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_prefs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_prefs_proto_rawDescGZIP(), []int{2}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PreferencesPatch struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FavoriteGenres    []string               `protobuf:"bytes,1,rep,name=favorite_genres,json=favoriteGenres,proto3" json:"favorite_genres,omitempty"`
	FavoriteGenresSet bool                   `protobuf:"varint,2,opt,name=favorite_genres_set,json=favoriteGenresSet,proto3" json:"favorite_genres_set,omitempty"`
	Language          string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	LanguageSet       bool                   `protobuf:"varint,4,opt,name=language_set,json=languageSet,proto3" json:"language_set,omitempty"`
	Nsfw              bool                   `protobuf:"varint,5,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	NsfwSet           bool                   `protobuf:"varint,6,opt,name=nsfw_set,json=nsfwSet,proto3" json:"nsfw_set,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PreferencesPatch) Reset() {
	*x = PreferencesPatch{}
	mi := &file_prefs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferencesPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferencesPatch) ProtoMessage() {}

func (x *PreferencesPatch) ProtoReflect() protoreflect.Message {
	mi := &file_prefs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferencesPatch.ProtoReflect.Descriptor instead.
func (*PreferencesPatch) Descriptor() ([]byte, []int) {
	return file_prefs_proto_rawDescGZIP(), []int{3}
}

func (x *PreferencesPatch) GetFavoriteGenres() []string {
	if x != nil {
		return x.FavoriteGenres
	}
	return nil
}

func (x *PreferencesPatch) GetFavoriteGenresSet() bool {
	if x != nil {
		return x.FavoriteGenresSet
	}
	return false
}

func (x *PreferencesPatch) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *PreferencesPatch) GetLanguageSet() bool {
	if x != nil {
		return x.LanguageSet
	}
	return false
}

func (x *PreferencesPatch) GetNsfw() bool {
	if x != nil {
		return x.Nsfw
	}
	return false
}

func (x *PreferencesPatch) GetNsfwSet() bool {
	if x != nil {
		return x.NsfwSet
	}
	return false
}

type UpdatePreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Patch         *PreferencesPatch      `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_prefs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_prefs_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetPatch() *PreferencesPatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_prefs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_prefs_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscribeRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_prefs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_prefs_proto_rawDescGZIP(), []int{6}
}

func (x *UnsubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnsubscribeRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_prefs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_prefs_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubscriptionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Subscription        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_prefs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prefs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_prefs_proto_rawDescGZIP(), []int{8}
}

func (x *ListSubscriptionsResponse) GetItems() []*Subscription {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_prefs_proto protoreflect.FileDescriptor

const file_prefs_proto_rawDesc = "" +
	"\n" +
	"\vprefs.proto\x12\x11mangahub.prefs.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\vPreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0ffavorite_genres\x18\x02 \x03(\tR\x0efavoriteGenres\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04nsfw\x18\x04 \x01(\bR\x04nsfw\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x86\x01\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xd9\x01\n" +
	"\x10PreferencesPatch\x12'\n" +
	"\x0ffavorite_genres\x18\x01 \x03(\tR\x0efavoriteGenres\x12.\n" +
	"\x13favorite_genres_set\x18\x02 \x01(\bR\x11favoriteGenresSet\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12!\n" +
	"\flanguage_set\x18\x04 \x01(\bR\vlanguageSet\x12\x12\n" +
	"\x04nsfw\x18\x05 \x01(\bR\x04nsfw\x12\x19\n" +
	"\bnsfw_set\x18\x06 \x01(\bR\ansfwSet\"n\n" +
	"\x18UpdatePreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\x05patch\x18\x02 \x01(\v2#.mangahub.prefs.v1.PreferencesPatchR\x05patch\"?\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"A\n" +
	"\x12UnsubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"3\n" +
	"\x18ListSubscriptionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x19ListSubscriptionsResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.mangahub.prefs.v1.SubscriptionR\x05items2\xe0\x03\n" +
	"\x0fUserPreferences\x12Z\n" +
	"\x0eGetPreferences\x12(.mangahub.prefs.v1.GetPreferencesRequest\x1a\x1e.mangahub.prefs.v1.Preferences\x12`\n" +
	"\x11UpdatePreferences\x12+.mangahub.prefs.v1.UpdatePreferencesRequest\x1a\x1e.mangahub.prefs.v1.Preferences\x12Q\n" +
	"\tSubscribe\x12#.mangahub.prefs.v1.SubscribeRequest\x1a\x1f.mangahub.prefs.v1.Subscription\x12L\n" +
	"\vUnsubscribe\x12%.mangahub.prefs.v1.UnsubscribeRequest\x1a\x16.google.protobuf.Empty\x12n\n" +
	"\x11ListSubscriptions\x12+.mangahub.prefs.v1.ListSubscriptionsRequest\x1a,.mangahub.prefs.v1.ListSubscriptionsResponseB(Z&mangahub-backend/proto/prefspb;prefspbb\x06proto3"

var (
	file_prefs_proto_rawDescOnce sync.Once
	file_prefs_proto_rawDescData []byte
)

func file_prefs_proto_rawDescGZIP() []byte {
	file_prefs_proto_rawDescOnce.Do(func() {
		file_prefs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prefs_proto_rawDesc), len(file_prefs_proto_rawDesc)))
	})
	return file_prefs_proto_rawDescData
}

var file_prefs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_prefs_proto_goTypes = []any{
	(*Preferences)(nil),               // 0: mangahub.prefs.v1.Preferences
	(*Subscription)(nil),              // 1: mangahub.prefs.v1.Subscription
	(*GetPreferencesRequest)(nil),     // 2: mangahub.prefs.v1.GetPreferencesRequest
	(*PreferencesPatch)(nil),          // 3: mangahub.prefs.v1.PreferencesPatch
	(*UpdatePreferencesRequest)(nil),  // 4: mangahub.prefs.v1.UpdatePreferencesRequest
	(*SubscribeRequest)(nil),          // 5: mangahub.prefs.v1.SubscribeRequest
	(*UnsubscribeRequest)(nil),        // 6: mangahub.prefs.v1.UnsubscribeRequest
	(*ListSubscriptionsRequest)(nil),  // 7: mangahub.prefs.v1.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil), // 8: mangahub.prefs.v1.ListSubscriptionsResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_prefs_proto_depIdxs = []int32{
	9,  // 0: mangahub.prefs.v1.Preferences.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 1: mangahub.prefs.v1.Subscription.created_at:type_name -> google.protobuf.Timestamp
	3,  // 2: mangahub.prefs.v1.UpdatePreferencesRequest.patch:type_name -> mangahub.prefs.v1.PreferencesPatch
	1,  // 3: mangahub.prefs.v1.ListSubscriptionsResponse.items:type_name -> mangahub.prefs.v1.Subscription
	2,  // 4: mangahub.prefs.v1.UserPreferences.GetPreferences:input_type -> mangahub.prefs.v1.GetPreferencesRequest
	4,  // 5: mangahub.prefs.v1.UserPreferences.UpdatePreferences:input_type -> mangahub.prefs.v1.UpdatePreferencesRequest
	5,  // 6: mangahub.prefs.v1.UserPreferences.Subscribe:input_type -> mangahub.prefs.v1.SubscribeRequest
	6,  // 7: mangahub.prefs.v1.UserPreferences.Unsubscribe:input_type -> mangahub.prefs.v1.UnsubscribeRequest
	7,  // 8: mangahub.prefs.v1.UserPreferences.ListSubscriptions:input_type -> mangahub.prefs.v1.ListSubscriptionsRequest
	0,  // 9: mangahub.prefs.v1.UserPreferences.GetPreferences:output_type -> mangahub.prefs.v1.Preferences
	0,  // 10: mangahub.prefs.v1.UserPreferences.UpdatePreferences:output_type -> mangahub.prefs.v1.Preferences
	1,  // 11: mangahub.prefs.v1.UserPreferences.Subscribe:output_type -> mangahub.prefs.v1.Subscription
	10, // 12: mangahub.prefs.v1.UserPreferences.Unsubscribe:output_type -> google.protobuf.Empty
	8,  // 13: mangahub.prefs.v1.UserPreferences.ListSubscriptions:output_type -> mangahub.prefs.v1.ListSubscriptionsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_prefs_proto_init() }
func file_prefs_proto_init() {
	if File_prefs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prefs_proto_rawDesc), len(file_prefs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prefs_proto_goTypes,
		DependencyIndexes: file_prefs_proto_depIdxs,
		MessageInfos:      file_prefs_proto_msgTypes,
	}.Build()
	File_prefs_proto = out.File
	file_prefs_proto_goTypes = nil
	file_prefs_proto_depIdxs = nil
}
