// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: catalog.proto

package catalogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalIds   map[string]string      `protobuf:"bytes,2,rep,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	AltTitles     []string               `protobuf:"bytes,4,rep,name=alt_titles,json=altTitles,proto3" json:"alt_titles,omitempty"`
	ArtistIds     []string               `protobuf:"bytes,5,rep,name=artist_ids,json=artistIds,proto3" json:"artist_ids,omitempty"`
	AuthorIds     []string               `protobuf:"bytes,6,rep,name=author_ids,json=authorIds,proto3" json:"author_ids,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Genres        []string               `protobuf:"bytes,9,rep,name=genres,proto3" json:"genres,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Chapters      int32                  `protobuf:"varint,11,opt,name=chapters,proto3" json:"chapters,omitempty"`
	Rating        float64                `protobuf:"fixed64,12,opt,name=rating,proto3" json:"rating,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,13,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Popularity    int32                  `protobuf:"varint,14,opt,name=popularity,proto3" json:"popularity,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetExternalIds() map[string]string {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAltTitles() []string {
	if x != nil {
		return x.AltTitles
	}
	return nil
}

func (x *Manga) GetArtistIds() []string {
	if x != nil {
		return x.ArtistIds
	}
	return nil
}

func (x *Manga) GetAuthorIds() []string {
	if x != nil {
		return x.AuthorIds
	}
	return nil
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manga) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Manga) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Manga) GetChapters() int32 {
	if x != nil {
		return x.Chapters
	}
	return 0
}

func (x *Manga) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Manga) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Manga) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *Manga) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Manga) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetMangaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMangaRequest) Reset() {
	*x = CreateMangaRequest{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMangaRequest) ProtoMessage() {}

func (x *CreateMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMangaRequest.ProtoReflect.Descriptor instead.
func (*CreateMangaRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMangaRequest) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type MangaPatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional fields use wrapper-like presence: client sets the *_set flag.
	Title          string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TitleSet       bool     `protobuf:"varint,2,opt,name=title_set,json=titleSet,proto3" json:"title_set,omitempty"`
	AltTitles      []string `protobuf:"bytes,3,rep,name=alt_titles,json=altTitles,proto3" json:"alt_titles,omitempty"`
	AltTitlesSet   bool     `protobuf:"varint,4,opt,name=alt_titles_set,json=altTitlesSet,proto3" json:"alt_titles_set,omitempty"`
	ArtistIds      []string `protobuf:"bytes,5,rep,name=artist_ids,json=artistIds,proto3" json:"artist_ids,omitempty"`
	ArtistIdsSet   bool     `protobuf:"varint,6,opt,name=artist_ids_set,json=artistIdsSet,proto3" json:"artist_ids_set,omitempty"`
	AuthorIds      []string `protobuf:"bytes,7,rep,name=author_ids,json=authorIds,proto3" json:"author_ids,omitempty"`
	AuthorIdsSet   bool     `protobuf:"varint,8,opt,name=author_ids_set,json=authorIdsSet,proto3" json:"author_ids_set,omitempty"`
	Description    string   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	DescriptionSet bool     `protobuf:"varint,10,opt,name=description_set,json=descriptionSet,proto3" json:"description_set,omitempty"`
	Status         string   `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	StatusSet      bool     `protobuf:"varint,12,opt,name=status_set,json=statusSet,proto3" json:"status_set,omitempty"`
	Genres         []string `protobuf:"bytes,13,rep,name=genres,proto3" json:"genres,omitempty"`
	GenresSet      bool     `protobuf:"varint,14,opt,name=genres_set,json=genresSet,proto3" json:"genres_set,omitempty"`
	Tags           []string `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	TagsSet        bool     `protobuf:"varint,16,opt,name=tags_set,json=tagsSet,proto3" json:"tags_set,omitempty"`
	Chapters       int32    `protobuf:"varint,17,opt,name=chapters,proto3" json:"chapters,omitempty"`
	ChaptersSet    bool     `protobuf:"varint,18,opt,name=chapters_set,json=chaptersSet,proto3" json:"chapters_set,omitempty"`
	Rating         float64  `protobuf:"fixed64,19,opt,name=rating,proto3" json:"rating,omitempty"`
	RatingSet      bool     `protobuf:"varint,20,opt,name=rating_set,json=ratingSet,proto3" json:"rating_set,omitempty"`
	CoverUrl       string   `protobuf:"bytes,21,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	CoverUrlSet    bool     `protobuf:"varint,22,opt,name=cover_url_set,json=coverUrlSet,proto3" json:"cover_url_set,omitempty"`
	Popularity     int32    `protobuf:"varint,23,opt,name=popularity,proto3" json:"popularity,omitempty"`
	PopularitySet  bool     `protobuf:"varint,24,opt,name=popularity_set,json=popularitySet,proto3" json:"popularity_set,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MangaPatch) Reset() {
	*x = MangaPatch{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaPatch) ProtoMessage() {}

func (x *MangaPatch) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaPatch.ProtoReflect.Descriptor instead.
func (*MangaPatch) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *MangaPatch) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MangaPatch) GetTitleSet() bool {
	if x != nil {
		return x.TitleSet
	}
	return false
}

func (x *MangaPatch) GetAltTitles() []string {
	if x != nil {
		return x.AltTitles
	}
	return nil
}

func (x *MangaPatch) GetAltTitlesSet() bool {
	if x != nil {
		return x.AltTitlesSet
	}
	return false
}

func (x *MangaPatch) GetArtistIds() []string {
	if x != nil {
		return x.ArtistIds
	}
	return nil
}

func (x *MangaPatch) GetArtistIdsSet() bool {
	if x != nil {
		return x.ArtistIdsSet
	}
	return false
}

func (x *MangaPatch) GetAuthorIds() []string {
	if x != nil {
		return x.AuthorIds
	}
	return nil
}

func (x *MangaPatch) GetAuthorIdsSet() bool {
	if x != nil {
		return x.AuthorIdsSet
	}
	return false
}

func (x *MangaPatch) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MangaPatch) GetDescriptionSet() bool {
	if x != nil {
		return x.DescriptionSet
	}
	return false
}

func (x *MangaPatch) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MangaPatch) GetStatusSet() bool {
	if x != nil {
		return x.StatusSet
	}
	return false
}

func (x *MangaPatch) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MangaPatch) GetGenresSet() bool {
	if x != nil {
		return x.GenresSet
	}
	return false
}

func (x *MangaPatch) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MangaPatch) GetTagsSet() bool {
	if x != nil {
		return x.TagsSet
	}
	return false
}

func (x *MangaPatch) GetChapters() int32 {
	if x != nil {
		return x.Chapters
	}
	return 0
}

func (x *MangaPatch) GetChaptersSet() bool {
	if x != nil {
		return x.ChaptersSet
	}
	return false
}

func (x *MangaPatch) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MangaPatch) GetRatingSet() bool {
	if x != nil {
		return x.RatingSet
	}
	return false
}

func (x *MangaPatch) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *MangaPatch) GetCoverUrlSet() bool {
	if x != nil {
		return x.CoverUrlSet
	}
	return false
}

func (x *MangaPatch) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *MangaPatch) GetPopularitySet() bool {
	if x != nil {
		return x.PopularitySet
	}
	return false
}

type UpdateMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Patch         *MangaPatch            `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMangaRequest) Reset() {
	*x = UpdateMangaRequest{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMangaRequest) ProtoMessage() {}

func (x *UpdateMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMangaRequest.ProtoReflect.Descriptor instead.
func (*UpdateMangaRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMangaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMangaRequest) GetPatch() *MangaPatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

type DeleteMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMangaRequest) Reset() {
	*x = DeleteMangaRequest{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMangaRequest) ProtoMessage() {}

func (x *DeleteMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMangaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMangaRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMangaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Genre         string                 `protobuf:"bytes,3,opt,name=genre,proto3" json:"genre,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Q             string                 `protobuf:"bytes,5,opt,name=q,proto3" json:"q,omitempty"`
	Sort          string                 `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMangaRequest) Reset() {
	*x = ListMangaRequest{}
	mi := &file_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangaRequest) ProtoMessage() {}

func (x *ListMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangaRequest.ProtoReflect.Descriptor instead.
func (*ListMangaRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListMangaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMangaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMangaRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *ListMangaRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListMangaRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListMangaRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type SearchMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMangaRequest) Reset() {
	*x = SearchMangaRequest{}
	mi := &file_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMangaRequest) ProtoMessage() {}

func (x *SearchMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMangaRequest.ProtoReflect.Descriptor instead.
func (*SearchMangaRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *SearchMangaRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMangaRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMangaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Manga               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMangaResponse) Reset() {
	*x = ListMangaResponse{}
	mi := &file_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangaResponse) ProtoMessage() {}

func (x *ListMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangaResponse.ProtoReflect.Descriptor instead.
func (*ListMangaResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *ListMangaResponse) GetItems() []*Manga {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMangaResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMangaResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMangaResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPopularMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPopularMangaRequest) Reset() {
	*x = GetPopularMangaRequest{}
	mi := &file_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPopularMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPopularMangaRequest) ProtoMessage() {}

func (x *GetPopularMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPopularMangaRequest.ProtoReflect.Descriptor instead.
func (*GetPopularMangaRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *GetPopularMangaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTrendingMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingMangaRequest) Reset() {
	*x = GetTrendingMangaRequest{}
	mi := &file_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingMangaRequest) ProtoMessage() {}

func (x *GetTrendingMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingMangaRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingMangaRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *GetTrendingMangaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMangaByArtistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistId      string                 `protobuf:"bytes,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMangaByArtistRequest) Reset() {
	*x = ListMangaByArtistRequest{}
	mi := &file_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangaByArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangaByArtistRequest) ProtoMessage() {}

func (x *ListMangaByArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangaByArtistRequest.ProtoReflect.Descriptor instead.
func (*ListMangaByArtistRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *ListMangaByArtistRequest) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *ListMangaByArtistRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMangaByArtistRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpsertMangaByExternalIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMangaByExternalIDsRequest) Reset() {
	*x = UpsertMangaByExternalIDsRequest{}
	mi := &file_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMangaByExternalIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMangaByExternalIDsRequest) ProtoMessage() {}

func (x *UpsertMangaByExternalIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMangaByExternalIDsRequest.ProtoReflect.Descriptor instead.
func (*UpsertMangaByExternalIDsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertMangaByExternalIDsRequest) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type UpsertMangaByExternalIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "insert" | "update"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMangaByExternalIDsResponse) Reset() {
	*x = UpsertMangaByExternalIDsResponse{}
	mi := &file_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMangaByExternalIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMangaByExternalIDsResponse) ProtoMessage() {}

func (x *UpsertMangaByExternalIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMangaByExternalIDsResponse.ProtoReflect.Descriptor instead.
func (*UpsertMangaByExternalIDsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertMangaByExternalIDsResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *UpsertMangaByExternalIDsResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\x13mangahub.catalog.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x04\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12N\n" +
	"\fexternal_ids\x18\x02 \x03(\v2+.mangahub.catalog.v1.Manga.ExternalIdsEntryR\vexternalIds\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"alt_titles\x18\x04 \x03(\tR\taltTitles\x12\x1d\n" +
	"\n" +
	"artist_ids\x18\x05 \x03(\tR\tartistIds\x12\x1d\n" +
	"\n" +
	"author_ids\x18\x06 \x03(\tR\tauthorIds\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x16\n" +
	"\x06genres\x18\t \x03(\tR\x06genres\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1a\n" +
	"\bchapters\x18\v \x01(\x05R\bchapters\x12\x16\n" +
	"\x06rating\x18\f \x01(\x01R\x06rating\x12\x1b\n" +
	"\tcover_url\x18\r \x01(\tR\bcoverUrl\x12\x1e\n" +
	"\n" +
	"popularity\x18\x0e \x01(\x05R\n" +
	"popularity\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a>\n" +
	"\x10ExternalIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x0fGetMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x12CreateMangaRequest\x120\n" +
	"\x05manga\x18\x01 \x01(\v2\x1a.mangahub.catalog.v1.MangaR\x05manga\"\xf4\x05\n" +
	"\n" +
	"MangaPatch\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1b\n" +
	"\ttitle_set\x18\x02 \x01(\bR\btitleSet\x12\x1d\n" +
	"\n" +
	"alt_titles\x18\x03 \x03(\tR\taltTitles\x12$\n" +
	"\x0ealt_titles_set\x18\x04 \x01(\bR\faltTitlesSet\x12\x1d\n" +
	"\n" +
	"artist_ids\x18\x05 \x03(\tR\tartistIds\x12$\n" +
	"\x0eartist_ids_set\x18\x06 \x01(\bR\fartistIdsSet\x12\x1d\n" +
	"\n" +
	"author_ids\x18\a \x03(\tR\tauthorIds\x12$\n" +
	"\x0eauthor_ids_set\x18\b \x01(\bR\fauthorIdsSet\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12'\n" +
	"\x0fdescription_set\x18\n" +
	" \x01(\bR\x0edescriptionSet\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"status_set\x18\f \x01(\bR\tstatusSet\x12\x16\n" +
	"\x06genres\x18\r \x03(\tR\x06genres\x12\x1d\n" +
	"\n" +
	"genres_set\x18\x0e \x01(\bR\tgenresSet\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tags\x12\x19\n" +
	"\btags_set\x18\x10 \x01(\bR\atagsSet\x12\x1a\n" +
	"\bchapters\x18\x11 \x01(\x05R\bchapters\x12!\n" +
	"\fchapters_set\x18\x12 \x01(\bR\vchaptersSet\x12\x16\n" +
	"\x06rating\x18\x13 \x01(\x01R\x06rating\x12\x1d\n" +
	"\n" +
	"rating_set\x18\x14 \x01(\bR\tratingSet\x12\x1b\n" +
	"\tcover_url\x18\x15 \x01(\tR\bcoverUrl\x12\"\n" +
	"\rcover_url_set\x18\x16 \x01(\bR\vcoverUrlSet\x12\x1e\n" +
	"\n" +
	"popularity\x18\x17 \x01(\x05R\n" +
	"popularity\x12%\n" +
	"\x0epopularity_set\x18\x18 \x01(\bR\rpopularitySet\"[\n" +
	"\x12UpdateMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x05patch\x18\x02 \x01(\v2\x1f.mangahub.catalog.v1.MangaPatchR\x05patch\"$\n" +
	"\x12DeleteMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x88\x01\n" +
	"\x10ListMangaRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\tR\x05genre\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\f\n" +
	"\x01q\x18\x05 \x01(\tR\x01q\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\tR\x04sort\"T\n" +
	"\x12SearchMangaRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x85\x01\n" +
	"\x11ListMangaResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.mangahub.catalog.v1.MangaR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\".\n" +
	"\x16GetPopularMangaRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"/\n" +
	"\x17GetTrendingMangaRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"a\n" +
	"\x18ListMangaByArtistRequest\x12\x1b\n" +
	"\tartist_id\x18\x01 \x01(\tR\bartistId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"S\n" +
	"\x1fUpsertMangaByExternalIDsRequest\x120\n" +
	"\x05manga\x18\x01 \x01(\v2\x1a.mangahub.catalog.v1.MangaR\x05manga\"l\n" +
	" UpsertMangaByExternalIDsResponse\x120\n" +
	"\x05manga\x18\x01 \x01(\v2\x1a.mangahub.catalog.v1.MangaR\x05manga\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action2\xd8\a\n" +
	"\fMangaCatalog\x12L\n" +
	"\bGetManga\x12$.mangahub.catalog.v1.GetMangaRequest\x1a\x1a.mangahub.catalog.v1.Manga\x12R\n" +
	"\vCreateManga\x12'.mangahub.catalog.v1.CreateMangaRequest\x1a\x1a.mangahub.catalog.v1.Manga\x12R\n" +
	"\vUpdateManga\x12'.mangahub.catalog.v1.UpdateMangaRequest\x1a\x1a.mangahub.catalog.v1.Manga\x12N\n" +
	"\vDeleteManga\x12'.mangahub.catalog.v1.DeleteMangaRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\tListManga\x12%.mangahub.catalog.v1.ListMangaRequest\x1a&.mangahub.catalog.v1.ListMangaResponse\x12^\n" +
	"\vSearchManga\x12'.mangahub.catalog.v1.SearchMangaRequest\x1a&.mangahub.catalog.v1.ListMangaResponse\x12f\n" +
	"\x0fGetPopularManga\x12+.mangahub.catalog.v1.GetPopularMangaRequest\x1a&.mangahub.catalog.v1.ListMangaResponse\x12h\n" +
	"\x10GetTrendingManga\x12,.mangahub.catalog.v1.GetTrendingMangaRequest\x1a&.mangahub.catalog.v1.ListMangaResponse\x12j\n" +
	"\x11ListMangaByArtist\x12-.mangahub.catalog.v1.ListMangaByArtistRequest\x1a&.mangahub.catalog.v1.ListMangaResponse\x12\x87\x01\n" +
	"\x18UpsertMangaByExternalIDs\x124.mangahub.catalog.v1.UpsertMangaByExternalIDsRequest\x1a5.mangahub.catalog.v1.UpsertMangaByExternalIDsResponseB,Z*mangahub-backend/proto/catalogpb;catalogpbb\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_catalog_proto_goTypes = []any{
	(*Manga)(nil),                            // 0: mangahub.catalog.v1.Manga
	(*GetMangaRequest)(nil),                  // 1: mangahub.catalog.v1.GetMangaRequest
	(*CreateMangaRequest)(nil),               // 2: mangahub.catalog.v1.CreateMangaRequest
	(*MangaPatch)(nil),                       // 3: mangahub.catalog.v1.MangaPatch
	(*UpdateMangaRequest)(nil),               // 4: mangahub.catalog.v1.UpdateMangaRequest
	(*DeleteMangaRequest)(nil),               // 5: mangahub.catalog.v1.DeleteMangaRequest
	(*ListMangaRequest)(nil),                 // 6: mangahub.catalog.v1.ListMangaRequest
	(*SearchMangaRequest)(nil),               // 7: mangahub.catalog.v1.SearchMangaRequest
	(*ListMangaResponse)(nil),                // 8: mangahub.catalog.v1.ListMangaResponse
	(*GetPopularMangaRequest)(nil),           // 9: mangahub.catalog.v1.GetPopularMangaRequest
	(*GetTrendingMangaRequest)(nil),          // 10: mangahub.catalog.v1.GetTrendingMangaRequest
	(*ListMangaByArtistRequest)(nil),         // 11: mangahub.catalog.v1.ListMangaByArtistRequest
	(*UpsertMangaByExternalIDsRequest)(nil),  // 12: mangahub.catalog.v1.UpsertMangaByExternalIDsRequest
	(*UpsertMangaByExternalIDsResponse)(nil), // 13: mangahub.catalog.v1.UpsertMangaByExternalIDsResponse
	nil,                                      // 14: mangahub.catalog.v1.Manga.ExternalIdsEntry
	(*timestamppb.Timestamp)(nil),            // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 16: google.protobuf.Empty
}
var file_catalog_proto_depIdxs = []int32{
	14, // 0: mangahub.catalog.v1.Manga.external_ids:type_name -> mangahub.catalog.v1.Manga.ExternalIdsEntry
	15, // 1: mangahub.catalog.v1.Manga.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: mangahub.catalog.v1.Manga.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: mangahub.catalog.v1.CreateMangaRequest.manga:type_name -> mangahub.catalog.v1.Manga
	3,  // 4: mangahub.catalog.v1.UpdateMangaRequest.patch:type_name -> mangahub.catalog.v1.MangaPatch
	0,  // 5: mangahub.catalog.v1.ListMangaResponse.items:type_name -> mangahub.catalog.v1.Manga
	0,  // 6: mangahub.catalog.v1.UpsertMangaByExternalIDsRequest.manga:type_name -> mangahub.catalog.v1.Manga
	0,  // 7: mangahub.catalog.v1.UpsertMangaByExternalIDsResponse.manga:type_name -> mangahub.catalog.v1.Manga
	1,  // 8: mangahub.catalog.v1.MangaCatalog.GetManga:input_type -> mangahub.catalog.v1.GetMangaRequest
	2,  // 9: mangahub.catalog.v1.MangaCatalog.CreateManga:input_type -> mangahub.catalog.v1.CreateMangaRequest
	4,  // 10: mangahub.catalog.v1.MangaCatalog.UpdateManga:input_type -> mangahub.catalog.v1.UpdateMangaRequest
	5,  // 11: mangahub.catalog.v1.MangaCatalog.DeleteManga:input_type -> mangahub.catalog.v1.DeleteMangaRequest
	6,  // 12: mangahub.catalog.v1.MangaCatalog.ListManga:input_type -> mangahub.catalog.v1.ListMangaRequest
	7,  // 13: mangahub.catalog.v1.MangaCatalog.SearchManga:input_type -> mangahub.catalog.v1.SearchMangaRequest
	9,  // 14: mangahub.catalog.v1.MangaCatalog.GetPopularManga:input_type -> mangahub.catalog.v1.GetPopularMangaRequest
	10, // 15: mangahub.catalog.v1.MangaCatalog.GetTrendingManga:input_type -> mangahub.catalog.v1.GetTrendingMangaRequest
	11, // 16: mangahub.catalog.v1.MangaCatalog.ListMangaByArtist:input_type -> mangahub.catalog.v1.ListMangaByArtistRequest
	12, // 17: mangahub.catalog.v1.MangaCatalog.UpsertMangaByExternalIDs:input_type -> mangahub.catalog.v1.UpsertMangaByExternalIDsRequest
	0,  // 18: mangahub.catalog.v1.MangaCatalog.GetManga:output_type -> mangahub.catalog.v1.Manga
	0,  // 19: mangahub.catalog.v1.MangaCatalog.CreateManga:output_type -> mangahub.catalog.v1.Manga
	0,  // 20: mangahub.catalog.v1.MangaCatalog.UpdateManga:output_type -> mangahub.catalog.v1.Manga
	16, // 21: mangahub.catalog.v1.MangaCatalog.DeleteManga:output_type -> google.protobuf.Empty
	8,  // 22: mangahub.catalog.v1.MangaCatalog.ListManga:output_type -> mangahub.catalog.v1.ListMangaResponse
	8,  // 23: mangahub.catalog.v1.MangaCatalog.SearchManga:output_type -> mangahub.catalog.v1.ListMangaResponse
	8,  // 24: mangahub.catalog.v1.MangaCatalog.GetPopularManga:output_type -> mangahub.catalog.v1.ListMangaResponse
	8,  // 25: mangahub.catalog.v1.MangaCatalog.GetTrendingManga:output_type -> mangahub.catalog.v1.ListMangaResponse
	8,  // 26: mangahub.catalog.v1.MangaCatalog.ListMangaByArtist:output_type -> mangahub.catalog.v1.ListMangaResponse
	13, // 27: mangahub.catalog.v1.MangaCatalog.UpsertMangaByExternalIDs:output_type -> mangahub.catalog.v1.UpsertMangaByExternalIDsResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
