// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: catalog.proto

package catalogpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MangaCatalog_GetManga_FullMethodName                 = "/mangahub.catalog.v1.MangaCatalog/GetManga"
	MangaCatalog_CreateManga_FullMethodName              = "/mangahub.catalog.v1.MangaCatalog/CreateManga"
	MangaCatalog_UpdateManga_FullMethodName              = "/mangahub.catalog.v1.MangaCatalog/UpdateManga"
	MangaCatalog_DeleteManga_FullMethodName              = "/mangahub.catalog.v1.MangaCatalog/DeleteManga"
	MangaCatalog_ListManga_FullMethodName                = "/mangahub.catalog.v1.MangaCatalog/ListManga"
	MangaCatalog_SearchManga_FullMethodName              = "/mangahub.catalog.v1.MangaCatalog/SearchManga"
	MangaCatalog_GetPopularManga_FullMethodName          = "/mangahub.catalog.v1.MangaCatalog/GetPopularManga"
	MangaCatalog_GetTrendingManga_FullMethodName         = "/mangahub.catalog.v1.MangaCatalog/GetTrendingManga"
	MangaCatalog_ListMangaByArtist_FullMethodName        = "/mangahub.catalog.v1.MangaCatalog/ListMangaByArtist"
	MangaCatalog_UpsertMangaByExternalIDs_FullMethodName = "/mangahub.catalog.v1.MangaCatalog/UpsertMangaByExternalIDs"
)

// MangaCatalogClient is the client API for MangaCatalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MangaCatalogClient interface {
	GetManga(ctx context.Context, in *GetMangaRequest, opts ...grpc.CallOption) (*Manga, error)
	CreateManga(ctx context.Context, in *CreateMangaRequest, opts ...grpc.CallOption) (*Manga, error)
	UpdateManga(ctx context.Context, in *UpdateMangaRequest, opts ...grpc.CallOption) (*Manga, error)
	DeleteManga(ctx context.Context, in *DeleteMangaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListManga(ctx context.Context, in *ListMangaRequest, opts ...grpc.CallOption) (*ListMangaResponse, error)
	SearchManga(ctx context.Context, in *SearchMangaRequest, opts ...grpc.CallOption) (*ListMangaResponse, error)
	GetPopularManga(ctx context.Context, in *GetPopularMangaRequest, opts ...grpc.CallOption) (*ListMangaResponse, error)
	GetTrendingManga(ctx context.Context, in *GetTrendingMangaRequest, opts ...grpc.CallOption) (*ListMangaResponse, error)
	ListMangaByArtist(ctx context.Context, in *ListMangaByArtistRequest, opts ...grpc.CallOption) (*ListMangaResponse, error)
	UpsertMangaByExternalIDs(ctx context.Context, in *UpsertMangaByExternalIDsRequest, opts ...grpc.CallOption) (*UpsertMangaByExternalIDsResponse, error)
}

type mangaCatalogClient struct {
	cc grpc.ClientConnInterface
}

func NewMangaCatalogClient(cc grpc.ClientConnInterface) MangaCatalogClient {
	return &mangaCatalogClient{cc}
}

func (c *mangaCatalogClient) GetManga(ctx context.Context, in *GetMangaRequest, opts ...grpc.CallOption) (*Manga, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manga)
	err := c.cc.Invoke(ctx, MangaCatalog_GetManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaCatalogClient) CreateManga(ctx context.Context, in *CreateMangaRequest, opts ...grpc.CallOption) (*Manga, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manga)
	err := c.cc.Invoke(ctx, MangaCatalog_CreateManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaCatalogClient) UpdateManga(ctx context.Context, in *UpdateMangaRequest, opts ...grpc.CallOption) (*Manga, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Manga)
	err := c.cc.Invoke(ctx, MangaCatalog_UpdateManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaCatalogClient) DeleteManga(ctx context.Context, in *DeleteMangaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MangaCatalog_DeleteManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaCatalogClient) ListManga(ctx context.Context, in *ListMangaRequest, opts ...grpc.CallOption) (*ListMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMangaResponse)
	err := c.cc.Invoke(ctx, MangaCatalog_ListManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaCatalogClient) SearchManga(ctx context.Context, in *SearchMangaRequest, opts ...grpc.CallOption) (*ListMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMangaResponse)
	err := c.cc.Invoke(ctx, MangaCatalog_SearchManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaCatalogClient) GetPopularManga(ctx context.Context, in *GetPopularMangaRequest, opts ...grpc.CallOption) (*ListMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMangaResponse)
	err := c.cc.Invoke(ctx, MangaCatalog_GetPopularManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaCatalogClient) GetTrendingManga(ctx context.Context, in *GetTrendingMangaRequest, opts ...grpc.CallOption) (*ListMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMangaResponse)
	err := c.cc.Invoke(ctx, MangaCatalog_GetTrendingManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaCatalogClient) ListMangaByArtist(ctx context.Context, in *ListMangaByArtistRequest, opts ...grpc.CallOption) (*ListMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMangaResponse)
	err := c.cc.Invoke(ctx, MangaCatalog_ListMangaByArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaCatalogClient) UpsertMangaByExternalIDs(ctx context.Context, in *UpsertMangaByExternalIDsRequest, opts ...grpc.CallOption) (*UpsertMangaByExternalIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertMangaByExternalIDsResponse)
	err := c.cc.Invoke(ctx, MangaCatalog_UpsertMangaByExternalIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MangaCatalogServer is the server API for MangaCatalog service.
// All implementations must embed UnimplementedMangaCatalogServer
// for forward compatibility.
type MangaCatalogServer interface {
	GetManga(context.Context, *GetMangaRequest) (*Manga, error)
	CreateManga(context.Context, *CreateMangaRequest) (*Manga, error)
	UpdateManga(context.Context, *UpdateMangaRequest) (*Manga, error)
	DeleteManga(context.Context, *DeleteMangaRequest) (*emptypb.Empty, error)
	ListManga(context.Context, *ListMangaRequest) (*ListMangaResponse, error)
	SearchManga(context.Context, *SearchMangaRequest) (*ListMangaResponse, error)
	GetPopularManga(context.Context, *GetPopularMangaRequest) (*ListMangaResponse, error)
	GetTrendingManga(context.Context, *GetTrendingMangaRequest) (*ListMangaResponse, error)
	ListMangaByArtist(context.Context, *ListMangaByArtistRequest) (*ListMangaResponse, error)
	UpsertMangaByExternalIDs(context.Context, *UpsertMangaByExternalIDsRequest) (*UpsertMangaByExternalIDsResponse, error)
	mustEmbedUnimplementedMangaCatalogServer()
}

// UnimplementedMangaCatalogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMangaCatalogServer struct{}

func (UnimplementedMangaCatalogServer) GetManga(context.Context, *GetMangaRequest) (*Manga, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManga not implemented")
}
func (UnimplementedMangaCatalogServer) CreateManga(context.Context, *CreateMangaRequest) (*Manga, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateManga not implemented")
}
func (UnimplementedMangaCatalogServer) UpdateManga(context.Context, *UpdateMangaRequest) (*Manga, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateManga not implemented")
}
func (UnimplementedMangaCatalogServer) DeleteManga(context.Context, *DeleteMangaRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteManga not implemented")
}
func (UnimplementedMangaCatalogServer) ListManga(context.Context, *ListMangaRequest) (*ListMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManga not implemented")
}
func (UnimplementedMangaCatalogServer) SearchManga(context.Context, *SearchMangaRequest) (*ListMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchManga not implemented")
}
func (UnimplementedMangaCatalogServer) GetPopularManga(context.Context, *GetPopularMangaRequest) (*ListMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularManga not implemented")
}
func (UnimplementedMangaCatalogServer) GetTrendingManga(context.Context, *GetTrendingMangaRequest) (*ListMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrendingManga not implemented")
}
func (UnimplementedMangaCatalogServer) ListMangaByArtist(context.Context, *ListMangaByArtistRequest) (*ListMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMangaByArtist not implemented")
}
func (UnimplementedMangaCatalogServer) UpsertMangaByExternalIDs(context.Context, *UpsertMangaByExternalIDsRequest) (*UpsertMangaByExternalIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertMangaByExternalIDs not implemented")
}
func (UnimplementedMangaCatalogServer) mustEmbedUnimplementedMangaCatalogServer() {}
func (UnimplementedMangaCatalogServer) testEmbeddedByValue()                      {}

// UnsafeMangaCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MangaCatalogServer will
// result in compilation errors.
type UnsafeMangaCatalogServer interface {
	mustEmbedUnimplementedMangaCatalogServer()
}

func RegisterMangaCatalogServer(s grpc.ServiceRegistrar, srv MangaCatalogServer) {
	// If the following call panics, it indicates UnimplementedMangaCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MangaCatalog_ServiceDesc, srv)
}

func _MangaCatalog_GetManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).GetManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_GetManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).GetManga(ctx, req.(*GetMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaCatalog_CreateManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).CreateManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_CreateManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).CreateManga(ctx, req.(*CreateMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaCatalog_UpdateManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).UpdateManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_UpdateManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).UpdateManga(ctx, req.(*UpdateMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaCatalog_DeleteManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).DeleteManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_DeleteManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).DeleteManga(ctx, req.(*DeleteMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaCatalog_ListManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).ListManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_ListManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).ListManga(ctx, req.(*ListMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaCatalog_SearchManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).SearchManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_SearchManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).SearchManga(ctx, req.(*SearchMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaCatalog_GetPopularManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).GetPopularManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_GetPopularManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).GetPopularManga(ctx, req.(*GetPopularMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaCatalog_GetTrendingManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).GetTrendingManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_GetTrendingManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).GetTrendingManga(ctx, req.(*GetTrendingMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaCatalog_ListMangaByArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMangaByArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).ListMangaByArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_ListMangaByArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).ListMangaByArtist(ctx, req.(*ListMangaByArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaCatalog_UpsertMangaByExternalIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertMangaByExternalIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaCatalogServer).UpsertMangaByExternalIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaCatalog_UpsertMangaByExternalIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaCatalogServer).UpsertMangaByExternalIDs(ctx, req.(*UpsertMangaByExternalIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MangaCatalog_ServiceDesc is the grpc.ServiceDesc for MangaCatalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MangaCatalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mangahub.catalog.v1.MangaCatalog",
	HandlerType: (*MangaCatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManga",
			Handler:    _MangaCatalog_GetManga_Handler,
		},
		{
			MethodName: "CreateManga",
			Handler:    _MangaCatalog_CreateManga_Handler,
		},
		{
			MethodName: "UpdateManga",
			Handler:    _MangaCatalog_UpdateManga_Handler,
		},
		{
			MethodName: "DeleteManga",
			Handler:    _MangaCatalog_DeleteManga_Handler,
		},
		{
			MethodName: "ListManga",
			Handler:    _MangaCatalog_ListManga_Handler,
		},
		{
			MethodName: "SearchManga",
			Handler:    _MangaCatalog_SearchManga_Handler,
		},
		{
			MethodName: "GetPopularManga",
			Handler:    _MangaCatalog_GetPopularManga_Handler,
		},
		{
			MethodName: "GetTrendingManga",
			Handler:    _MangaCatalog_GetTrendingManga_Handler,
		},
		{
			MethodName: "ListMangaByArtist",
			Handler:    _MangaCatalog_ListMangaByArtist_Handler,
		},
		{
			MethodName: "UpsertMangaByExternalIDs",
			Handler:    _MangaCatalog_UpsertMangaByExternalIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}
