FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 go build -o /out/tcp-server ./cmd/tcp-server

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/tcp-server /tcp-server
EXPOSE 9000 9100
ENTRYPOINT ["/tcp-server"]
