// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: progress.proto

package progresspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReadingProgress_UpsertProgress_FullMethodName   = "/mangahub.progress.v1.ReadingProgress/UpsertProgress"
	ReadingProgress_GetProgress_FullMethodName      = "/mangahub.progress.v1.ReadingProgress/GetProgress"
	ReadingProgress_ListUserProgress_FullMethodName = "/mangahub.progress.v1.ReadingProgress/ListUserProgress"
	ReadingProgress_DeleteProgress_FullMethodName   = "/mangahub.progress.v1.ReadingProgress/DeleteProgress"
	ReadingProgress_Stats_FullMethodName            = "/mangahub.progress.v1.ReadingProgress/Stats"
)

// ReadingProgressClient is the client API for ReadingProgress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReadingProgressClient interface {
	UpsertProgress(ctx context.Context, in *UpsertProgressRequest, opts ...grpc.CallOption) (*Progress, error)
	GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*Progress, error)
	ListUserProgress(ctx context.Context, in *ListUserProgressRequest, opts ...grpc.CallOption) (*ListUserProgressResponse, error)
	DeleteProgress(ctx context.Context, in *DeleteProgressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type readingProgressClient struct {
	cc grpc.ClientConnInterface
}

func NewReadingProgressClient(cc grpc.ClientConnInterface) ReadingProgressClient {
	return &readingProgressClient{cc}
}

func (c *readingProgressClient) UpsertProgress(ctx context.Context, in *UpsertProgressRequest, opts ...grpc.CallOption) (*Progress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Progress)
	err := c.cc.Invoke(ctx, ReadingProgress_UpsertProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingProgressClient) GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*Progress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Progress)
	err := c.cc.Invoke(ctx, ReadingProgress_GetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingProgressClient) ListUserProgress(ctx context.Context, in *ListUserProgressRequest, opts ...grpc.CallOption) (*ListUserProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserProgressResponse)
	err := c.cc.Invoke(ctx, ReadingProgress_ListUserProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingProgressClient) DeleteProgress(ctx context.Context, in *DeleteProgressRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ReadingProgress_DeleteProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingProgressClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, ReadingProgress_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadingProgressServer is the server API for ReadingProgress service.
// All implementations must embed UnimplementedReadingProgressServer
// for forward compatibility.
type ReadingProgressServer interface {
	UpsertProgress(context.Context, *UpsertProgressRequest) (*Progress, error)
	GetProgress(context.Context, *GetProgressRequest) (*Progress, error)
	ListUserProgress(context.Context, *ListUserProgressRequest) (*ListUserProgressResponse, error)
	DeleteProgress(context.Context, *DeleteProgressRequest) (*emptypb.Empty, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedReadingProgressServer()
}

// UnimplementedReadingProgressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReadingProgressServer struct{}

func (UnimplementedReadingProgressServer) UpsertProgress(context.Context, *UpsertProgressRequest) (*Progress, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertProgress not implemented")
}
func (UnimplementedReadingProgressServer) GetProgress(context.Context, *GetProgressRequest) (*Progress, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgress not implemented")
}
func (UnimplementedReadingProgressServer) ListUserProgress(context.Context, *ListUserProgressRequest) (*ListUserProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserProgress not implemented")
}
func (UnimplementedReadingProgressServer) DeleteProgress(context.Context, *DeleteProgressRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProgress not implemented")
}
func (UnimplementedReadingProgressServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedReadingProgressServer) mustEmbedUnimplementedReadingProgressServer() {}
func (UnimplementedReadingProgressServer) testEmbeddedByValue()                         {}

// UnsafeReadingProgressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadingProgressServer will
// result in compilation errors.
type UnsafeReadingProgressServer interface {
	mustEmbedUnimplementedReadingProgressServer()
}

func RegisterReadingProgressServer(s grpc.ServiceRegistrar, srv ReadingProgressServer) {
	// If the following call panics, it indicates UnimplementedReadingProgressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReadingProgress_ServiceDesc, srv)
}

func _ReadingProgress_UpsertProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingProgressServer).UpsertProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingProgress_UpsertProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingProgressServer).UpsertProgress(ctx, req.(*UpsertProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingProgress_GetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingProgressServer).GetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingProgress_GetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingProgressServer).GetProgress(ctx, req.(*GetProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingProgress_ListUserProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingProgressServer).ListUserProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingProgress_ListUserProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingProgressServer).ListUserProgress(ctx, req.(*ListUserProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingProgress_DeleteProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingProgressServer).DeleteProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingProgress_DeleteProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingProgressServer).DeleteProgress(ctx, req.(*DeleteProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingProgress_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingProgressServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingProgress_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingProgressServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadingProgress_ServiceDesc is the grpc.ServiceDesc for ReadingProgress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadingProgress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mangahub.progress.v1.ReadingProgress",
	HandlerType: (*ReadingProgressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertProgress",
			Handler:    _ReadingProgress_UpsertProgress_Handler,
		},
		{
			MethodName: "GetProgress",
			Handler:    _ReadingProgress_GetProgress_Handler,
		},
		{
			MethodName: "ListUserProgress",
			Handler:    _ReadingProgress_ListUserProgress_Handler,
		},
		{
			MethodName: "DeleteProgress",
			Handler:    _ReadingProgress_DeleteProgress_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _ReadingProgress_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "progress.proto",
}
