// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: progress.proto

package progresspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Progress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId        string                 `protobuf:"bytes,3,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // reading | completed | plan_to_read | dropped
	CurrentChapter int32                  `protobuf:"varint,5,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Rating         float64                `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"`
	LastReadAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_read_at,json=lastReadAt,proto3" json:"last_read_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{0}
}

func (x *Progress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Progress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Progress) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *Progress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Progress) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *Progress) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Progress) GetLastReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReadAt
	}
	return nil
}

type UpsertProgressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId        string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,4,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Rating         float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertProgressRequest) Reset() {
	*x = UpsertProgressRequest{}
	mi := &file_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProgressRequest) ProtoMessage() {}

func (x *UpsertProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProgressRequest.ProtoReflect.Descriptor instead.
func (*UpsertProgressRequest) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *UpsertProgressRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpsertProgressRequest) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *UpsertProgressRequest) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_progress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{2}
}

func (x *GetProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type ListUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserProgressRequest) Reset() {
	*x = ListUserProgressRequest{}
	mi := &file_progress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserProgressRequest) ProtoMessage() {}

func (x *ListUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserProgressRequest.ProtoReflect.Descriptor instead.
func (*ListUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserProgressRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListUserProgressRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserProgressRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListUserProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Progress            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserProgressResponse) Reset() {
	*x = ListUserProgressResponse{}
	mi := &file_progress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserProgressResponse) ProtoMessage() {}

func (x *ListUserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserProgressResponse.ProtoReflect.Descriptor instead.
func (*ListUserProgressResponse) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserProgressResponse) GetItems() []*Progress {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUserProgressResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserProgressResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserProgressResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProgressRequest) Reset() {
	*x = DeleteProgressRequest{}
	mi := &file_progress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProgressRequest) ProtoMessage() {}

func (x *DeleteProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProgressRequest.ProtoReflect.Descriptor instead.
func (*DeleteProgressRequest) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_progress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{6}
}

func (x *StatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Buckets keyed by status name (e.g. "reading", "completed", ...).
	Buckets       map[string]int32 `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_progress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_progress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_progress_proto_rawDescGZIP(), []int{7}
}

func (x *StatsResponse) GetBuckets() map[string]int32 {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_progress_proto protoreflect.FileDescriptor

const file_progress_proto_rawDesc = "" +
	"\n" +
	"\x0eprogress.proto\x12\x14mangahub.progress.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x01\n" +
	"\bProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x03 \x01(\tR\amangaId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_chapter\x18\x05 \x01(\x05R\x0ecurrentChapter\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x01R\x06rating\x12<\n" +
	"\flast_read_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastReadAt\"\xa4\x01\n" +
	"\x15UpsertProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_chapter\x18\x04 \x01(\x05R\x0ecurrentChapter\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\"H\n" +
	"\x12GetProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\"t\n" +
	"\x17ListUserProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x90\x01\n" +
	"\x18ListUserProgressResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.mangahub.progress.v1.ProgressR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"K\n" +
	"\x15DeleteProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\"'\n" +
	"\fStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x97\x01\n" +
	"\rStatsResponse\x12J\n" +
	"\abuckets\x18\x01 \x03(\v20.mangahub.progress.v1.StatsResponse.BucketsEntryR\abuckets\x1a:\n" +
	"\fBucketsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\xe5\x03\n" +
	"\x0fReadingProgress\x12]\n" +
	"\x0eUpsertProgress\x12+.mangahub.progress.v1.UpsertProgressRequest\x1a\x1e.mangahub.progress.v1.Progress\x12W\n" +
	"\vGetProgress\x12(.mangahub.progress.v1.GetProgressRequest\x1a\x1e.mangahub.progress.v1.Progress\x12q\n" +
	"\x10ListUserProgress\x12-.mangahub.progress.v1.ListUserProgressRequest\x1a..mangahub.progress.v1.ListUserProgressResponse\x12U\n" +
	"\x0eDeleteProgress\x12+.mangahub.progress.v1.DeleteProgressRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x05Stats\x12\".mangahub.progress.v1.StatsRequest\x1a#.mangahub.progress.v1.StatsResponseB.Z,mangahub-backend/proto/progresspb;progresspbb\x06proto3"

var (
	file_progress_proto_rawDescOnce sync.Once
	file_progress_proto_rawDescData []byte
)

func file_progress_proto_rawDescGZIP() []byte {
	file_progress_proto_rawDescOnce.Do(func() {
		file_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_progress_proto_rawDesc), len(file_progress_proto_rawDesc)))
	})
	return file_progress_proto_rawDescData
}

var file_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_progress_proto_goTypes = []any{
	(*Progress)(nil),                 // 0: mangahub.progress.v1.Progress
	(*UpsertProgressRequest)(nil),    // 1: mangahub.progress.v1.UpsertProgressRequest
	(*GetProgressRequest)(nil),       // 2: mangahub.progress.v1.GetProgressRequest
	(*ListUserProgressRequest)(nil),  // 3: mangahub.progress.v1.ListUserProgressRequest
	(*ListUserProgressResponse)(nil), // 4: mangahub.progress.v1.ListUserProgressResponse
	(*DeleteProgressRequest)(nil),    // 5: mangahub.progress.v1.DeleteProgressRequest
	(*StatsRequest)(nil),             // 6: mangahub.progress.v1.StatsRequest
	(*StatsResponse)(nil),            // 7: mangahub.progress.v1.StatsResponse
	nil,                              // 8: mangahub.progress.v1.StatsResponse.BucketsEntry
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 10: google.protobuf.Empty
}
var file_progress_proto_depIdxs = []int32{
	9,  // 0: mangahub.progress.v1.Progress.last_read_at:type_name -> google.protobuf.Timestamp
	0,  // 1: mangahub.progress.v1.ListUserProgressResponse.items:type_name -> mangahub.progress.v1.Progress
	8,  // 2: mangahub.progress.v1.StatsResponse.buckets:type_name -> mangahub.progress.v1.StatsResponse.BucketsEntry
	1,  // 3: mangahub.progress.v1.ReadingProgress.UpsertProgress:input_type -> mangahub.progress.v1.UpsertProgressRequest
	2,  // 4: mangahub.progress.v1.ReadingProgress.GetProgress:input_type -> mangahub.progress.v1.GetProgressRequest
	3,  // 5: mangahub.progress.v1.ReadingProgress.ListUserProgress:input_type -> mangahub.progress.v1.ListUserProgressRequest
	5,  // 6: mangahub.progress.v1.ReadingProgress.DeleteProgress:input_type -> mangahub.progress.v1.DeleteProgressRequest
	6,  // 7: mangahub.progress.v1.ReadingProgress.Stats:input_type -> mangahub.progress.v1.StatsRequest
	0,  // 8: mangahub.progress.v1.ReadingProgress.UpsertProgress:output_type -> mangahub.progress.v1.Progress
	0,  // 9: mangahub.progress.v1.ReadingProgress.GetProgress:output_type -> mangahub.progress.v1.Progress
	4,  // 10: mangahub.progress.v1.ReadingProgress.ListUserProgress:output_type -> mangahub.progress.v1.ListUserProgressResponse
	10, // 11: mangahub.progress.v1.ReadingProgress.DeleteProgress:output_type -> google.protobuf.Empty
	7,  // 12: mangahub.progress.v1.ReadingProgress.Stats:output_type -> mangahub.progress.v1.StatsResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_progress_proto_init() }
func file_progress_proto_init() {
	if File_progress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_progress_proto_rawDesc), len(file_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_progress_proto_goTypes,
		DependencyIndexes: file_progress_proto_depIdxs,
		MessageInfos:      file_progress_proto_msgTypes,
	}.Build()
	File_progress_proto = out.File
	file_progress_proto_goTypes = nil
	file_progress_proto_depIdxs = nil
}
